version: "3.8"

networks:
  sample_net:

services:
  rabbitmq:
    image: rabbitmq:3.11.8-management
    container_name: rabbitmq-sample
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    networks:
      - sample_net
    restart: unless-stopped




